version: "3.1"
services:
  nginx-proxy:
    image: nginxproxy/nginx-proxy:alpine
    container_name: nginx-proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./certs:/etc/nginx/certs:ro
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ./conf/client_max_body_size.conf:/etc/nginx/conf.d/client_max_body_size.conf
      - ./vhost:/etc/nginx/vhost.d
      - ./html:/usr/share/nginx/html
    restart: unless-stopped


# echo "127.0.0.1 $DOMAIN" | sudo tee -a /etc/hosts
# docker network create nginx-proxy
networks:
  default:
    external:
      name: nginx-proxy
